export const API_ENDPOINTS = {
  REGISTER: "/api/v1/auth/register",
  LOGIN: "/api/v1/auth/login",
  VERIFY_EMAIL: "/api/v1/auth/verify-email",
  RESEND_VERIFICATION: "/api/v1/auth/resend-verification",
  FORGOT_PASSWORD: "/api/v1/auth/forgot-password",
  RESET_PASSWORD: "/api/v1/auth/reset-password",
  WHOAMI: "/api/v1/auth/whoami",
  UPDATE_PROFILE: "/api/v1/auth/update",
  UPDATE_PASSWORD: "/api/v1/auth/update-password",
  ADMIN_USERS: "/api/v1/admin/users",
  PRODUCTS: "/api/v1/products",
  ADMIN_PRODUCTS: "/api/v1/admin/products",
  CATEGORIES: "/api/v1/categories",
  ADMIN_CATEGORIES: "/api/v1/admin/categories",
  DEALS: "/api/v1/deals",
  ADMIN_DEALS: "/api/v1/admin/deals",
  CART: "/api/v1/cart",
  WISHLIST: "/api/v1/wishlist",
  ORDERS: "/api/v1/orders",
  ADMIN_ORDERS: "/api/v1/admin/orders",
  SUPPORT: "/api/v1/support",
  ADMIN_SUPPORT: "/api/v1/admin/support",
  ADMIN_UPLOAD_CATEGORY_IMAGE: "/api/v1/admin/uploads/category-image",
  ADMIN_UPLOAD_PRODUCT_IMAGE: "/api/v1/admin/uploads/product-image",
  ADMIN_UPLOAD_DEAL_IMAGE: "/api/v1/admin/uploads/deal-image",
  CHAT: "/api/v1/chat",
};
